name: acervo_fisico
description: Ferramenta de localização e controle do acervo físico do Arquivo Técnico da ITAIPU Binacional.

# Após cada alteração neste arquivo executar no terminal:
# flutter pub get

# Para publicar a versão no servidor local executar no terminal:
# flutter build web

# Para criar app para Android executar:
# 1) flutter build appbundle --split-debug-info
#  
# Para publicar no github pages executar:
# 1) flutter pub global run peanut:peanut
# 2) git push origin --set-upstream gh-pages


# Para gerar a versão para Android tipo appbundle
# Shrinking your code with R8
# R8 is the new code shrinker from Google, and it’s enabled by default when you build a release APK or AAB. 
# To disable R8, pass the --no-shrink flag to flutter build apk or flutter build appbundle.
# flutter build appbundle --no-shrink

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.2"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2
  connectivity_plus: ^1.4.0
  intl: ^0.17.0
  parse_server_sdk_flutter: ^3.1.0
  share: ^2.0.4
  flutter_modular: ^4.2.0 # para trabalhar melhor com Routes
  url_strategy: ^0.2.0 # para remover o hash '#' das URLs
  uni_links: ^0.5.1 # para trabalhar com links externos (qrcode)
  pdf: ^3.6.1 # para criar arquivos PDF
  printing: ^5.6.1 # para visualizar arquivos PDF
  open_file: ^3.2.1 # para abrir arquivos nos sistemas operacionais
  path_provider: ^2.0.6 # para descobrir caminho nos sistemas operacionais
  url_launcher: ^6.0.12 # para abrir URLs na web
  package_info_plus: ^1.3.0 # para extrair informações do app

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  #flutter_launcher_icons: "^0.9.2"
  #flutter_launcher_name: "^0.0.1"

flutter_icons:
  image_path: 'assets/icons/ic_launcher.png'
  android: true
  ios: true
  # Executar: flutter pub run flutter_launcher_icons:main

flutter_launcher_name:
  name: 'Acervo Físico ENCA.DT'
  # Executar: flutter pub run flutter_launcher_name:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/ic_launcher.png
    - assets/icons/ufo.png
    - assets/icons/band-aid.png
    - assets/icons/private-key.png
    - assets/icons/data-management.png
    - assets/icons/magician.png
    - assets/images/caixaA3.png
    - assets/images/caixaA4.png
    - assets/images/gaveta.png
    - assets/images/indefinido.png
    - assets/images/pastaA3.png
    - assets/images/tubo.png
    - assets/etiqueta.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Baumans
      fonts:
        - asset: assets/fonts/Baumans-Regular.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Regular.ttf
    - family: MavenPro
      fonts:
        - asset: assets/fonts/MavenPro-Regular.ttf
        - asset: assets/fonts/MavenPro-Bold.ttf
          weight: 700
  #         style: italic
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
